require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Gui::LogicsController do

  # This should return the minimal set of attributes required to create a valid
  # Gui::Logic. As you add validations to Gui::Logic, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Gui::LogicsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all gui_logics as @gui_logics" do
      logic = Gui::Logic.create! valid_attributes
      get :index, {}, valid_session
      assigns(:gui_logics).should eq([logic])
    end
  end

  describe "GET show" do
    it "assigns the requested gui_logic as @gui_logic" do
      logic = Gui::Logic.create! valid_attributes
      get :show, {:id => logic.to_param}, valid_session
      assigns(:gui_logic).should eq(logic)
    end
  end

  describe "GET new" do
    it "assigns a new gui_logic as @gui_logic" do
      get :new, {}, valid_session
      assigns(:gui_logic).should be_a_new(Gui::Logic)
    end
  end

  describe "GET edit" do
    it "assigns the requested gui_logic as @gui_logic" do
      logic = Gui::Logic.create! valid_attributes
      get :edit, {:id => logic.to_param}, valid_session
      assigns(:gui_logic).should eq(logic)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Gui::Logic" do
        expect {
          post :create, {:gui_logic => valid_attributes}, valid_session
        }.to change(Gui::Logic, :count).by(1)
      end

      it "assigns a newly created gui_logic as @gui_logic" do
        post :create, {:gui_logic => valid_attributes}, valid_session
        assigns(:gui_logic).should be_a(Gui::Logic)
        assigns(:gui_logic).should be_persisted
      end

      it "redirects to the created gui_logic" do
        post :create, {:gui_logic => valid_attributes}, valid_session
        response.should redirect_to(Gui::Logic.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved gui_logic as @gui_logic" do
        # Trigger the behavior that occurs when invalid params are submitted
        Gui::Logic.any_instance.stub(:save).and_return(false)
        post :create, {:gui_logic => {}}, valid_session
        assigns(:gui_logic).should be_a_new(Gui::Logic)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Gui::Logic.any_instance.stub(:save).and_return(false)
        post :create, {:gui_logic => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested gui_logic" do
        logic = Gui::Logic.create! valid_attributes
        # Assuming there are no other gui_logics in the database, this
        # specifies that the Gui::Logic created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Gui::Logic.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => logic.to_param, :gui_logic => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested gui_logic as @gui_logic" do
        logic = Gui::Logic.create! valid_attributes
        put :update, {:id => logic.to_param, :gui_logic => valid_attributes}, valid_session
        assigns(:gui_logic).should eq(logic)
      end

      it "redirects to the gui_logic" do
        logic = Gui::Logic.create! valid_attributes
        put :update, {:id => logic.to_param, :gui_logic => valid_attributes}, valid_session
        response.should redirect_to(logic)
      end
    end

    describe "with invalid params" do
      it "assigns the gui_logic as @gui_logic" do
        logic = Gui::Logic.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Gui::Logic.any_instance.stub(:save).and_return(false)
        put :update, {:id => logic.to_param, :gui_logic => {}}, valid_session
        assigns(:gui_logic).should eq(logic)
      end

      it "re-renders the 'edit' template" do
        logic = Gui::Logic.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Gui::Logic.any_instance.stub(:save).and_return(false)
        put :update, {:id => logic.to_param, :gui_logic => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested gui_logic" do
      logic = Gui::Logic.create! valid_attributes
      expect {
        delete :destroy, {:id => logic.to_param}, valid_session
      }.to change(Gui::Logic, :count).by(-1)
    end

    it "redirects to the gui_logics list" do
      logic = Gui::Logic.create! valid_attributes
      delete :destroy, {:id => logic.to_param}, valid_session
      response.should redirect_to(gui_logics_url)
    end
  end

end
