require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Gui::PanelsController do

  # This should return the minimal set of attributes required to create a valid
  # Gui::Panel. As you add validations to Gui::Panel, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Gui::PanelsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all gui_panels as @gui_panels" do
      panel = Gui::Panel.create! valid_attributes
      get :index, {}, valid_session
      assigns(:gui_panels).should eq([panel])
    end
  end

  describe "GET show" do
    it "assigns the requested gui_panel as @gui_panel" do
      panel = Gui::Panel.create! valid_attributes
      get :show, {:id => panel.to_param}, valid_session
      assigns(:gui_panel).should eq(panel)
    end
  end

  describe "GET new" do
    it "assigns a new gui_panel as @gui_panel" do
      get :new, {}, valid_session
      assigns(:gui_panel).should be_a_new(Gui::Panel)
    end
  end

  describe "GET edit" do
    it "assigns the requested gui_panel as @gui_panel" do
      panel = Gui::Panel.create! valid_attributes
      get :edit, {:id => panel.to_param}, valid_session
      assigns(:gui_panel).should eq(panel)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Gui::Panel" do
        expect {
          post :create, {:gui_panel => valid_attributes}, valid_session
        }.to change(Gui::Panel, :count).by(1)
      end

      it "assigns a newly created gui_panel as @gui_panel" do
        post :create, {:gui_panel => valid_attributes}, valid_session
        assigns(:gui_panel).should be_a(Gui::Panel)
        assigns(:gui_panel).should be_persisted
      end

      it "redirects to the created gui_panel" do
        post :create, {:gui_panel => valid_attributes}, valid_session
        response.should redirect_to(Gui::Panel.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved gui_panel as @gui_panel" do
        # Trigger the behavior that occurs when invalid params are submitted
        Gui::Panel.any_instance.stub(:save).and_return(false)
        post :create, {:gui_panel => {}}, valid_session
        assigns(:gui_panel).should be_a_new(Gui::Panel)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Gui::Panel.any_instance.stub(:save).and_return(false)
        post :create, {:gui_panel => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested gui_panel" do
        panel = Gui::Panel.create! valid_attributes
        # Assuming there are no other gui_panels in the database, this
        # specifies that the Gui::Panel created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Gui::Panel.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => panel.to_param, :gui_panel => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested gui_panel as @gui_panel" do
        panel = Gui::Panel.create! valid_attributes
        put :update, {:id => panel.to_param, :gui_panel => valid_attributes}, valid_session
        assigns(:gui_panel).should eq(panel)
      end

      it "redirects to the gui_panel" do
        panel = Gui::Panel.create! valid_attributes
        put :update, {:id => panel.to_param, :gui_panel => valid_attributes}, valid_session
        response.should redirect_to(panel)
      end
    end

    describe "with invalid params" do
      it "assigns the gui_panel as @gui_panel" do
        panel = Gui::Panel.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Gui::Panel.any_instance.stub(:save).and_return(false)
        put :update, {:id => panel.to_param, :gui_panel => {}}, valid_session
        assigns(:gui_panel).should eq(panel)
      end

      it "re-renders the 'edit' template" do
        panel = Gui::Panel.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Gui::Panel.any_instance.stub(:save).and_return(false)
        put :update, {:id => panel.to_param, :gui_panel => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested gui_panel" do
      panel = Gui::Panel.create! valid_attributes
      expect {
        delete :destroy, {:id => panel.to_param}, valid_session
      }.to change(Gui::Panel, :count).by(-1)
    end

    it "redirects to the gui_panels list" do
      panel = Gui::Panel.create! valid_attributes
      delete :destroy, {:id => panel.to_param}, valid_session
      response.should redirect_to(gui_panels_url)
    end
  end

end
