require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Gui::ViewKeyInfosController do

  # This should return the minimal set of attributes required to create a valid
  # Gui::ViewKeyInfo. As you add validations to Gui::ViewKeyInfo, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Gui::ViewKeyInfosController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all gui_view_key_infos as @gui_view_key_infos" do
      view_key_info = Gui::ViewKeyInfo.create! valid_attributes
      get :index, {}, valid_session
      assigns(:gui_view_key_infos).should eq([view_key_info])
    end
  end

  describe "GET show" do
    it "assigns the requested gui_view_key_info as @gui_view_key_info" do
      view_key_info = Gui::ViewKeyInfo.create! valid_attributes
      get :show, {:id => view_key_info.to_param}, valid_session
      assigns(:gui_view_key_info).should eq(view_key_info)
    end
  end

  describe "GET new" do
    it "assigns a new gui_view_key_info as @gui_view_key_info" do
      get :new, {}, valid_session
      assigns(:gui_view_key_info).should be_a_new(Gui::ViewKeyInfo)
    end
  end

  describe "GET edit" do
    it "assigns the requested gui_view_key_info as @gui_view_key_info" do
      view_key_info = Gui::ViewKeyInfo.create! valid_attributes
      get :edit, {:id => view_key_info.to_param}, valid_session
      assigns(:gui_view_key_info).should eq(view_key_info)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Gui::ViewKeyInfo" do
        expect {
          post :create, {:gui_view_key_info => valid_attributes}, valid_session
        }.to change(Gui::ViewKeyInfo, :count).by(1)
      end

      it "assigns a newly created gui_view_key_info as @gui_view_key_info" do
        post :create, {:gui_view_key_info => valid_attributes}, valid_session
        assigns(:gui_view_key_info).should be_a(Gui::ViewKeyInfo)
        assigns(:gui_view_key_info).should be_persisted
      end

      it "redirects to the created gui_view_key_info" do
        post :create, {:gui_view_key_info => valid_attributes}, valid_session
        response.should redirect_to(Gui::ViewKeyInfo.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved gui_view_key_info as @gui_view_key_info" do
        # Trigger the behavior that occurs when invalid params are submitted
        Gui::ViewKeyInfo.any_instance.stub(:save).and_return(false)
        post :create, {:gui_view_key_info => {}}, valid_session
        assigns(:gui_view_key_info).should be_a_new(Gui::ViewKeyInfo)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Gui::ViewKeyInfo.any_instance.stub(:save).and_return(false)
        post :create, {:gui_view_key_info => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested gui_view_key_info" do
        view_key_info = Gui::ViewKeyInfo.create! valid_attributes
        # Assuming there are no other gui_view_key_infos in the database, this
        # specifies that the Gui::ViewKeyInfo created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Gui::ViewKeyInfo.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => view_key_info.to_param, :gui_view_key_info => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested gui_view_key_info as @gui_view_key_info" do
        view_key_info = Gui::ViewKeyInfo.create! valid_attributes
        put :update, {:id => view_key_info.to_param, :gui_view_key_info => valid_attributes}, valid_session
        assigns(:gui_view_key_info).should eq(view_key_info)
      end

      it "redirects to the gui_view_key_info" do
        view_key_info = Gui::ViewKeyInfo.create! valid_attributes
        put :update, {:id => view_key_info.to_param, :gui_view_key_info => valid_attributes}, valid_session
        response.should redirect_to(view_key_info)
      end
    end

    describe "with invalid params" do
      it "assigns the gui_view_key_info as @gui_view_key_info" do
        view_key_info = Gui::ViewKeyInfo.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Gui::ViewKeyInfo.any_instance.stub(:save).and_return(false)
        put :update, {:id => view_key_info.to_param, :gui_view_key_info => {}}, valid_session
        assigns(:gui_view_key_info).should eq(view_key_info)
      end

      it "re-renders the 'edit' template" do
        view_key_info = Gui::ViewKeyInfo.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Gui::ViewKeyInfo.any_instance.stub(:save).and_return(false)
        put :update, {:id => view_key_info.to_param, :gui_view_key_info => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested gui_view_key_info" do
      view_key_info = Gui::ViewKeyInfo.create! valid_attributes
      expect {
        delete :destroy, {:id => view_key_info.to_param}, valid_session
      }.to change(Gui::ViewKeyInfo, :count).by(-1)
    end

    it "redirects to the gui_view_key_infos list" do
      view_key_info = Gui::ViewKeyInfo.create! valid_attributes
      delete :destroy, {:id => view_key_info.to_param}, valid_session
      response.should redirect_to(gui_view_key_infos_url)
    end
  end

end
